services:
  http-web-app:
    build: 
      # image: websockets/http-web-app:latest
      context: ./http-web-app
      args:
        - PORT=3000
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
        interval: 5s
        retries: 5
        start_period: 15s
        timeout: 5s

  https-web-app:
    build:
      context: ./https-web-app
      args:
          - PORT=3001
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./certs:/etc/ssl/certs

  websockets-web-app:
    build: ./websockets-web-app
    ports:
      - "4000:4000"

  wss-web-app:
    build: ./wss-web-app
    ports:
      - "4001:4001"
    volumes:
      - ./certs:/etc/ssl/certs